title: Just the Docs Template
description: A starter template for a Jekyll site using the Just the Docs theme!
theme: just-the-docs

url: https://devichand579.github.io
baseurl: /HPT

aux_links:
  Template Repository: 
    - https://github.com/devichand579/HPT
plugins:
  - jekyll-default-layout

navigation:
  - title: Home
    url: https://devichand579.github.io/HPT

  - title: Documentation
    url: https://devichand579.github.io/HPT/documentation/

  - title: Leaderboard
    url: https://devichand579.github.io/HPT/leaderboard/